### ISSUE TITLE
Can this be added to homebrew?

### ISSUE THREAD

**Issue by MDTech-us-MAN** [marcusbritanicus/libarchive-qt#3]
Hello,

It would be great if this could be added to OS X homebrew.
As stated in issue #2 the build didn't work on the examples, but before I even got to that, I had to add the following to `lib/lib.pro`:
`QMAKE_LFLAGS += -L/usr/local/opt/libarchive/lib -L/usr/local/opt/xz/lib`
`INCLUDEPATH += /usr/local/opt/libarchive/include /usr/local/opt/xz/include`
I installed `libarchive` (and `xz`/`lama`) using `brew install libarchive`.

**Comment by marcusbritanicus** [comment]
Well to be frank, this was not built for OS X. I only have linux, and have no idea about OS X. I guess the modification required is due unusual path where the packages are installed. In linux we have it in /usr/lib/ or /usr/local/lib and the compiler knows to search there.

Since I do not know much about OS X, you can, if you know how, feel free to add it to homebrew.

**Comment by marcusbritanicus** [comment]
Is `/usr/local/opt/....` the usual path where libarchive and xz are installed in all OS X systems? If so I'll modify the qmake file to compile without modificaitons.

**Comment by MDTech-us-MAN** [comment]
That's where Homebrew places stuff. Since Homebrew is the only package manager for OS X, I'd guess you'd call it a standard.

**Comment by marcusbritanicus** [comment]
I've added the `QMAKE_FLAGS` and `INCLUDEPATH` for mac. If you know how to add the project to homebrew, feel free to do so. However before you can install, you'll have to set the install and other variables in lib.pro
